// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_CfnX7C-dnrhbrnhG2ZS_Y-m4JjEHSg',
    appId: '1:496509143528:web:9367b3da0aa1257a017c5d',
    messagingSenderId: '496509143528',
    projectId: 'notes-919bc',
    authDomain: 'notes-919bc.firebaseapp.com',
    storageBucket: 'notes-919bc.firebasestorage.app',
    measurementId: 'G-N2C6Y66J0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74MatYPEnyxaherWAfK6lEHl1bfnFbic',
    appId: '1:496509143528:android:301ef21b7595a678017c5d',
    messagingSenderId: '496509143528',
    projectId: 'notes-919bc',
    storageBucket: 'notes-919bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjIaRi7YPvXLav8jtsONAMMOOIwKlfo9Q',
    appId: '1:496509143528:ios:0f58e26b24fa4a7c017c5d',
    messagingSenderId: '496509143528',
    projectId: 'notes-919bc',
    storageBucket: 'notes-919bc.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjIaRi7YPvXLav8jtsONAMMOOIwKlfo9Q',
    appId: '1:496509143528:ios:0f58e26b24fa4a7c017c5d',
    messagingSenderId: '496509143528',
    projectId: 'notes-919bc',
    storageBucket: 'notes-919bc.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0_CfnX7C-dnrhbrnhG2ZS_Y-m4JjEHSg',
    appId: '1:496509143528:web:0b1cc990a487e497017c5d',
    messagingSenderId: '496509143528',
    projectId: 'notes-919bc',
    authDomain: 'notes-919bc.firebaseapp.com',
    storageBucket: 'notes-919bc.firebasestorage.app',
    measurementId: 'G-RGSCXBE7Q0',
  );
}
